### PR TITLE
Fix Account Redirect

### LINKED ISSUE #663: BUG: broken account dropdown
# Symptom
* if I am a member of a group (not an organizer) clicking "account" in the nav dropdown redirects to `/home` instead my account edit page

### PR DESCRIPTION
**Pull request by vaughanj10**
Closes #663 
_______________________

* **BUG:** if I am a member of a group (not an organizer) clicking "account" in the nav dropdown redirects to /home instead my account edit page
* **CAUSE:** group-based permissions only allow organizers to edit a group member
* **FIX:** introduced person-based permissions and allow a person to edit themselves

### CODE REVIEW

File: app/models/ability.rb [hunk 1]
```diff
@@ -11,6 +11,21 @@ def initialize(current_user, current_group=nil)
         person.groups.include?(current_group)
       end
 
+      can :manage, Person do |person|
+        permitted_flag = false
+        permitted_flag = true if person == current_user
+        permitted_flag = true if Membership.organizer.exists?(group: current_group, person: current_user)
```
Comment (aguestuser) [inline app/models/ability.rb]: for my own edification: are we allowed to write `current_user`? i thought we had to write `current_person`?

File: app/models/ability.rb [hunk 2]
```diff
@@ -11,6 +11,21 @@ def initialize(current_user, current_group=nil)
         person.groups.include?(current_group)
       end
 
+      can :manage, Person do |person|
```
Comment (aguestuser) [inline app/models/ability.rb]: later, if we were worried about performance (which i'm not ATM), i'd wonder whether it was worth trying to optimize these sql queries a bit (since we hit them every time we try to perform this auth check, and in the case where a group is affiliated with many other groups, we might rack up a few). but we're not worried about that. so just flagging it for later so we think about it now and can remember if we need to. (also maybe worth looking at whether permission-checking is expensive on pages where we *know* we're currently having perf issues?)

**Comment by aguestuser** [comment]
# Notes for QA'ing

* **BUG:**if I am a member of a group (not an organizer) clicking "account" in the nav dropdown redirects to /home instead my account edit page
* **CAUSE:** group-based permissions only allow organizers to edit a group member
* **FIX:** introduced person-based permissions and allow a person to edit themselves

**Comment by aguestuser** [comment]
Okay! QA'ed this on staging and it works under conditions described above. Let's :shipit: !!!
